<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    public function run()
    {
        DB::table('menus')->insert([
            [
                'id' => 1,
                'title' => 'dashboard',
                'icon' => 'mdi-view-dashboard',
                'route' => '/dashboard',
                'permission_key' => null,
                'parent_id' => null,
                'order' => 0,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => '2025-07-29 10:12:57',
            ],
            [
                'id' => 2,
                'title' => 'Pages',
                'icon' => 'mdi-file-document-edit',
                'route' => '/pages',
                'permission_key' => 'page.view',
                'parent_id' => 7,
                'order' => 1,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => '2025-07-29 10:12:57',
            ],
            [
                'id' => 3,
                'title' => 'Users',
                'icon' => 'mdi-account-multiple',
                'route' => null,
                'permission_key' => 'user.view',
                'parent_id' => null,
                'order' => 2,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => '2025-07-29 10:12:57',
            ],
            [
                'id' => 4,
                'title' => 'users',
                'icon' => 'mdi-account',
                'route' => '/users',
                'permission_key' => 'user.view',
                'parent_id' => 3,
                'order' => 0,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => '2025-07-29 10:12:57',
            ],
            [
                'id' => 5,
                'title' => 'Roles',
                'icon' => 'mdi-account-check',
                'route' => '/roles',
                'permission_key' => 'role.view',
                'parent_id' => 3,
                'order' => 1,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => '2025-07-29 10:12:57',
            ],
            [
                'id' => 6,
                'title' => 'Permissions',
                'icon' => 'mdi-account-details',
                'route' => '/permissions',
                'permission_key' => 'permission.view',
                'parent_id' => 3,
                'order' => 2,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => '2025-07-29 10:12:57',
            ],
            [
                'id' => 7,
                'title' => 'system',
                'icon' => 'mdi-cog-box',
                'route' => null,
                'permission_key' => 'setting.view',
                'parent_id' => null,
                'order' => 3,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => '2025-07-29 10:12:57',
            ],
            [
                'id' => 8,
                'title' => 'settings',
                'icon' => 'mdi-cog',
                'route' => '/settings',
                'permission_key' => 'setting.update',
                'parent_id' => 7,
                'order' => 0,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => '2025-07-29 10:12:57',
            ],
            [
                'id' => 9,
                'title' => 'Menu',
                'icon' => 'mdi-format-list-bulleted-square',
                'route' => '/menus',
                'permission_key' => 'menu.view',
                'parent_id' => 7,
                'order' => 1,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => '2025-07-29 10:12:57',
            ],
            [
                'id' => 10,
                'title' => 'log_activity',
                'icon' => 'mdi-database-eye',
                'route' => '/logs',
                'permission_key' => 'log.view',
                'parent_id' => 7,
                'order' => 2,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => '2025-07-29 10:12:57',
            ],
            [
                'id' => 11,
                'title' => 'Backup DB',
                'icon' => 'mdi-database',
                'route' => '/backups',
                'permission_key' => 'backup.view',
                'parent_id' => 7,
                'order' => 3,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => '2025-07-29 10:12:57',
            ],
        ]);
    }
}
